### ISSUE TITLE
All options are gray in sublime 3

### ISSUE THREAD

**Issue by nomi-ramzan** [dexbol/sublime-TortoiseSVN#37]
Hi
I am using sublime 3  and this plugin.
I checked both settings ( default + user ). Both are fine. But still I am getting all options disabled.

**Comment by aadrii** [comment]
You can fix it by editting the TortoiseSVN.py file, the line 30 contains an error, and should be in a single line, or ends with a backslash to tell its a multi line command : 
cmd = '"' + tortoiseproc_path + '"' + \
            ' /command:' + cmd + ' /path:"%s"' % dir
or cmd = '"' + tortoiseproc_path + '"' + ' /command:' + cmd + ' /path:"%s"' % dir

**Comment by nomi-ramzan** [comment]
Thank you @aadrii it is working for me now.
